#!/bin/bash

update=`checkupdates | wc -l`
mail=`python ~/scripts/gmail_unread`

if (( update > 0 )); then
	echo -e "You have $update updates available" 
elif (( mail > 0 )); then
	echo -e "You have $mail unread messages"
fi
