#!/bin/bash

LOC="207931"
URL="http://www.accuweather.com/en/ie/dublin/207931/weather-forecast/$LOC"

while true 
	do
	notify-send -u low -t 5000 "$(wget -q -o /dev/null -O- "$URL" | awk -F\' '/acm_RecentLocationsCarousel\.push/{print $2": dublin, ireland "$12"°" }' | head -1)"
	sleep 3600
done
