#!/bin/bash

NAME="RennOfTheMill"
TYPE="7day"
SIZE="5x5"
CAPTION="true"
IMGDIR="/mnt/c/Users/Shane/Pictures/4chan/mu/collage.jpg"

echo -e "\nGenerating Last.FM collage..."

curl -s "http://www.tapmusic.net/collage.php?user=$NAME&type=$TYPE&size=$SIZE&caption=$CAPTION" --compressed > $IMGDIR 

echo -e "\nYour Last.FM collage has been saved at $IMGDIR"
