#!/bin/bash

## variables {{
OUTPUT_ART="/tmp/cover.png"
ART_WIDTH="80x80"
MDIR="/mnt/f/"
FILE="$(mpc current -f %file% | sed -e 's/%20/ /g;s/%5B/[/g;s/%5D/]/g')"
FILE="${FILE/local:track:}"
FILENAME="${MDIR}${FILE}"
SDIR="$(dirname "$FILENAME" | head -n1)"
IMG_NAME="(cover|folder|front|art)\.(jpg|png|gif)$"
FIND="$(find "$SDIR/" -maxdepth 1 -type f | egrep -i -m1 "$IMG_NAME")"
## }}

## if cover doesn't exist, extract one using ffmpeg 
if [[ ! -n $FIND ]]; then
	ffmpeg -y -i "$FILENAME" "$OUTPUT_ART" 2&>1 >/dev/null
else
	cp "$FIND" "$OUTPUT_ART"	
fi
## }}

## resize the cover {{
mogrify -resize "$ART_WIDTH" "$OUTPUT_ART"
## }}

## pipe the info to dunst {{
notify-send -u normal "Now Playing" "$(mpc current)" -i $OUTPUT_ART
## }}
