#!/bin/bash

# download an album on slsk and use this
# script to create an entry in your library
# and copy the download over

## variables {{
SLSKDIR="/mnt/c/Users/Shane/Documents/Soulseek Downloads/complete" # soulseek dl folder
BRWSRDIR="/mnt/i/E-Downloads" # downloads folder
OUTPUTDIR="/mnt/f" # music library
TMP="./tmp.txt" # temp file containing probed tags
## }}

## disable case sensitivity {{
shopt -s nocaseglob
## }}

## check for dependencies {{
if [[ "$(dpkg -s ffmpeg 2&>1 >/dev/null)" ]]; then
   while true; do
	echo "FFmpeg is required, but not installed."
	read -p "Do you wish to install it now?" YN
	   case $YN in
		[yY]* ) sudo apt-get install ffmpeg; break;;
		[nN]* ) echo "Chose not to install dependencies. Terminating."; exit;;
		    * ) echo "Invalid input, please answer \"y\" or \"n\".";;
	   esac
   done
fi	
## }}

## user inputs {{
input() {
	read -rp "Album: " ALBUM
}
## }}

## fetch info from ID3 tags {{
probe() {
	ffprobe "$(find ./*.mp3 | head -n1)" 2>&1 | grep -w "artist\\|date" | head -n2 | sed 's/    date            : //g;s/    artist          : //g' >> $TMP
	ARTIST=$(sed 's/ feat. .*//g;s/ (feat. .*)//g;1q;d' "${TMP}")
	YEAR=$(sed '2q;d' "${TMP}")
}
## }}

## create entry in library {{
mkDIR() {
	if [ ! -d "$OUTPUTDIR/$ARTIST/\\[$YEAR\\] $ALBUM" ]; then
		mkdir -p "${OUTPUTDIR}/${ARTIST}/[${YEAR}] ${ALBUM}"
	fi
}
## }}

## extract archive {{
extract() {
	find ./ -iname "*${ALBUM}*.zip" -print0 | while IFS= read -r -d ''; do
		unzip ./*"${ALBUM}"*.zip
		rm -rf ./*"${ALBUM}"*.zip
	done
	find ./ -iname "*${ALBUM}*.rar" -print0 | while IFS= read -r -d ''; do
		unrar x -ad ./*"${ALBUM}"*.rar
	done
}
## }}

## decide how to copy files over based on user input option {{
while [ ! $# -eq 0 ]; do
	case "$1" in
	--slsk)
		input
		cd "${SLSKDIR}" || { echo "Could not find Soulseek directory!"; return 1; }
		cd ./*"${ALBUM}"* || { echo "Could not find ${ALBUM}!"; return 1; }
		probe
		mkDIR
		cp -r ./* "${OUTPUTDIR}/${ARTIST}/[${YEAR}] ${ALBUM}"
		rm "${OUTPUTDIR}/${ARTIST}/[${YEAR}] ${ALBUM}/${TMP}"
		cd ..
		rm -rf ./*"${ALBUM}"*
	;;
	--browser)
		input
		cd "${BRWSRDIR}" || { echo "Could not find Download directory!"; return 1; }	
		extract
		cd ./*"${ALBUM}"* || { echo "Could not find find ${ALBUM}!"; return 1; }
		probe
		mkDIR
		cp -r ./* "${OUTPUTDIR}/${ARTIST}/[${YEAR}] ${ALBUM}"
		rm "${OUTPUTDIR}/${ARTIST}/[${YEAR}] ${ALBUM}/${TMP}"
		cd ..
		rm -rf ./*"${ALBUM}"*
	;;
	--flac2mp3)
		echo "test successful"
	;;
	--help)
		echo -e "\\n	--slsk			select soulseek dl folder"
		echo -e "\\n	--browser		select web browser dl folder"
	;;
	*)
		echo -e "\\nWelcome to muDL, please see --help for details\\n"
	;;
  	esac
    shift
done	
## }}

## enable case sensitivity {{
shopt -u nocaseglob
## }}
